replicaCount: 1
applicationName: practical-dapr

image:
  repository: dapracr.azurecr.io/dapr-product-catalog-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

service:
  type: ClusterIP
  appPort: 5201
  httpPort: 5202
  grpcPort: 5203

ingress:
  enabled: false

# resources:
#   limits:
#     cpu: "500m"
#   requests:
#     cpu: "100m"

# nodeSelector:
#   "kubernetes.io/os": linux

# tolerations: []

# affinity: {}

env:
  values:
    - name: DAPR_HTTP_PORT
      value: 5202
    - name: Services__ProductCatalogService__RestUri
      value: http://localhost:5202
    - name: Services__InventoryService__GrpcUri
      value: http://inventory-api:5303

# probes:
#   liveness:
#     path: /liveness
#     initialDelaySeconds: 20
#     periodSeconds: 30
#     port: http
