{{- $name := include "inventory.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "inventory.fullname" . }}
  labels:
    app: {{ template "inventory.name" . }}
    chart: {{ template "inventory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "inventory.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "inventory.name" . }}
        release: {{ .Release.Name }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: inventory-api
        dapr.io/port: {{ .Values.service.appPort }}
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
    spec:
      {{ if .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{ range .Values.imagePullSecrets -}}
        - name: {{ .name }}
      {{- end -}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}
          ports:
            - name: apphttp
              containerPort: 5201
              protocol: TCP
            - name: httpPort
              containerPort: 5202
              protocol: TCP
            - name: grpcPort
              containerPort: 5203
              protocol: TCP
          # {{ if .Values.probes -}}
          # {{- if .Values.probes.liveness -}}
          # livenessProbe:
          #   httpGet:
          #     port: {{ .Values.probes.liveness.port }}
          #     path: {{ .Values.probes.liveness.path }}
          #   initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          # {{- end -}}
          # {{- end -}}
          # {{- if .Values.probes -}}
          # {{- if .Values.probes.readiness }}
          # readinessProbe:
          #   httpGet:
          #     port: {{ .Values.probes.readiness.port }}
          #     path: {{ .Values.probes.readiness.path }}
          #   initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          #   timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          # {{- end -}}
          # {{- end }}
#           resources:
# {{ toYaml .Values.resources | indent 12 }}
#     {{- with .Values.nodeSelector }}

