apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: {{ template "inventory.name" . }}
    chart: {{ template "inventory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: apphttp
      protocol: TCP
      name: apphttp
    - port: {{ .Values.service.httpPort }}
      targetPort: httpPort
      protocol: TCP
      name: httpPort
    - port: {{ .Values.service.httpPort }}
      targetPort: grpcPort
      protocol: TCP
      name: grpcPort
  selector:
    app: {{ template "inventory.name" . }}
    release: {{ .Release.Name }}
