name: graphql-ci

on:
  push:
    branches:
      - master
      - feature/*
    paths:
      - "src/GraphApi/**"
      - "src/BuildingBlocks/**"
      - ".github/workflows/graph-api.yml"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.event.path }}
    - run: |
          git fetch --unshallow
    
    - uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101 

    - name: Build with dotnet
      run: dotnet build src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj --configuration Release
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        workdir: ./src/GraphApi/CoolStore.GraphApi
        registry: docker.pkg.github.com
