name: product-catalog-ci

on:
  push:
    branches:
      - master
      - feature/*
    paths:
      - "src/ProductCatalog/**"
      - "src/BuildingBlocks/**"
      - ".github/workflows/product-catalog-api.yml"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.event.path }}
    - run: |
          git fetch --unshallow
    
    - uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101 

    - name: Build with dotnet
      run: dotnet build src/ProductCatalog/CoolStore.ProductCatalogApi/CoolStore.ProductCatalogApi.csproj --configuration Release
    
    - name: Build docker image
      run: docker build . --file ./src/ProductCatalog/CoolStore.ProductCatalogApi/Dockerfile --tag latest
    
    - name: Log into registry
      run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    
    - name: Push image
      run: |
        VERSION=$NBGV_SemVer2
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/dapr-product-catalog-api
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
  
    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GH_TOKEN }}
    #     workdir: ./src/ProductCatalog/CoolStore.ProductCatalogApi
    #     registry: docker.pkg.github.com
